### ISSUE TITLE
page becomes unresponsive on infinite loops

### ISSUE THREAD

**Issue by vjsevill** [kennethtruong/pagrader#30]
I'm grading cs5f5_PA2 on Windows 7 in Chome.  I noticed that when a student has an infinite loop in their code. The page becomes unresponsive and the browser requests to kill the page.  As an example, for you to test, i was working on the PA2 for cs5fer.

**Comment by kennethtruong** [comment]
Ohh thanks for pointing it out! I'll fix it later tonight. I think if you don't kill the page it should be able to load. The student's output file is really big because of the infinite loop which causes the page to become unresponsive. But yea I'll update the script so I don't save the output for those students with infinite loops.

**Comment by kennethtruong** [comment]
If it doesn't load for you. Send me an email with the student's score and comment and I'll update the student's score/comment for you so that you can submit your grades

**Comment by kennethtruong** [comment]
I fixed it so that the student's output file only includes `Program terminated because of infinite loop. Please run their program manually or check their code.` that way it won't be take so long to load. Thanks for submitting an issue! :D
